---
#TODO: Generate fake cert to default to in conf so the directives are there for certbot to hook to.

- stat:
    path: /etc/nginx/proxies-available/http-forward.conf
  register: is_installed

- include: setup.yml
  when: is_installed.stat.exists == False

- name: LOADBALANCER | Include proxy_conf nginx.conf
  lineinfile:
    path: /etc/nginx/nginx.conf
    line: "include /etc/nginx/proxy_conf; \n"
    regexp: "^include /etc/nginx/proxy_conf;"
    state: present
    insertafter: "^http {\n"

- include: proxy-confs.yml
  with_dict: "{{ proxies }}"
  loop_control:
    loop_var: outer_item