---
- name: LOADBALANCER | Check if SSL exists
  stat:
    path: "/etc/letsencrypt/live/{{ outer_item.value.domain }}/fullchain.pem"
  register: ssl_cert

- block:
    - name: LOADBALANCER | Create proxy confs for HTTP
      template:
        src: nginx/http-proxy.conf.jinja2
        dest: "/etc/nginx/proxies-available/{{ outer_item.key }}.conf"
      register: changed_http_confs

    - name: LOADBALANCER | Enable HTTP proxy confs
      file:
        src: "/etc/nginx/proxies-available/{{ outer_item.key }}.conf"
        dest: "/etc/nginx/proxies-enabled/{{ outer_item.key }}.conf"
        state: link
      when: changed_http_confs.changed

  when: outer_item.value.type is undefined or type == "http"

- block:
    - name: LOADBALANCER | Create proxy confs for streams
      template:
        src: nginx/stream-proxy.conf.jinja2
        dest: "/etc/nginx/proxies-available/{{ outer_item.key }}:{{ outer_item.value.port }}.conf"
      register: changed_stream_confs

    - name: LOADBALANCER | Enable stream proxy confs
      file:
        src: "/etc/nginx/proxies-available/{{ outer_item.key }}:{{ outer_item.value.port }}.conf"
        dest: "/etc/nginx/proxies-enabled/{{ outer_item.key }}:{{ outer_item.value.port }}.conf"
        state: link
      when: changed_stream_confs.changed

  when: outer_item.value.type == "stream"

- block:
    - file:
        path: /etc/nginx/basix-auth
        state: directory
        owner: root
        group: nginx

    - htpasswd:
        path: /etc/nginx/basix-auth/.passwd_{{ outer_item.value.domain }}
        name: "{{ outer_item.value.basic_auth.name }}"
        password: "{{ outer_item.value.basic_auth.password }}"
        owner: root
        group: nginx
        mode: 0640

  when: outer_item.value.basic_auth is defined