---
- name: LOADBALANCER | Check if SSL exists
  stat:
    path: "/etc/letsencrypt/live/{{ outer_item.value.domain }}/fullchain.pem"
  register: ssl_cert

- name: LOADBALANCER | Create proxy confs
  template:
    src: nginx/proxy.conf.jinja2
    dest: "/etc/nginx/proxies-available/{{ outer_item.key }}.conf"
  register: changed_confs

- name: LOADBALANCER | Enable proxy confs
  file:
    src: "/etc/nginx/proxies-available/{{ outer_item.key }}.conf"
    dest: "/etc/nginx/proxies-enabled/{{ outer_item.key }}.conf"
    state: link
  when: changed_confs.changed

- block:
    - debug:
        var: outer_item.value
    
    - file:
        path: /etc/nginx/basix-auth
        state: directory
        owner: root
        group: nginx

    - htpasswd:
        path: /etc/nginx/basix-auth/.passwd_{{ outer_item.value.domain }}
        name: "{{ item.name }}"
        password: "{{ item.password }}"
        owner: root
        group: nginx
        mode: 0640
      with_items: outer_item.value.basic_auth

  when: outer_item.value.basic_auth is defined