---
- name: LOADBAlANCER | Install needed packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ loadbalancer_needed_packages }}"

- name: LOADBALANCER | Move proxy_conf to /etc/nginx
  copy:
    src: proxy_conf
    dest: /etc/nginx/proxy_conf

- name: LOADBALANCER | Create proxies-available folder
  file:
    path: /etc/nginx/proxies-available/
    state: directory

- name: LOADBALANCER | Create proxies-enabled folder
  file:
    path: /etc/nginx/proxies-enabled/
    state: directory

- name: LOADBALANCER | Create letsencrypt folder
  file:
    path: /usr/share/nginx/letsencrypt
    state: directory

- name: LOADBALANCER | Create http to https forward
  template:
    src: nginx/http-forward.conf.jinja2
    dest: /etc/nginx/proxies-available/http-forward.conf

- name: LOADBALANCER | Enable http to https forward
  file:
    src: /etc/nginx/proxies-available/http-forward.conf
    dest: /etc/nginx/proxies-enabled/http-forward.conf
    state: link

- name: LOADBALANCER | Enable EPOLL in nginx.conf
  lineinfile:
    path: /etc/nginx/nginx.conf
    line: "use epoll; \n"
    state: present
    insertafter: "^events {\n"
