---
- name: LOADBAlANCER | Yum install needed packages
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ loadbalancer_yum_packages }}"
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: LOADBAlANCER | Apt install needed packages
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ loadbalancer_apt_packages }}"
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: LOADBALANCER | Move proxy_conf to /etc/nginx
  copy:
    src: proxy_conf
    dest: /etc/nginx/proxy_conf

- name: LOADBALANCER | Create proxies-available folder
  file:
    path: /etc/nginx/proxies-available/
    state: directory

- name: LOADBALANCER | Create proxies-enabled folder
  file:
    path: /etc/nginx/proxies-enabled/
    state: directory

- name: LOADBALANCER | Create letsencrypt folder
  file:
    path: /usr/share/nginx/letsencrypt
    state: directory

- name: LOADBALANCER | Create rewrites http > https
  template:
    src: nginx/http-rewrite.conf.jinja2
    dest: /etc/nginx/proxies-available/http-rewrite.conf

- name: LOADBALANCER | Enable rewrites http > https
  file:
    src: /etc/nginx/proxies-available/http-rewrite.conf
    dest: /etc/nginx/proxies-enabled/http-rewrite.conf
    state: link

- name: LOADBALANCER | Enable EPOLL in nginx.conf
  lineinfile:
    path: /etc/nginx/nginx.conf
    line: "use epoll; \n"
    state: present
    insertafter: "^events {\n"
